### PR TITLE
Automatically inject the extern definition for a dynamic import alias

### LINKED ISSUE #3829: Omitting the extern for a dynamic import alias causes a crash
If the `--dynamic_import_alias` flag is used, but a definition for the alias is not provided, the compiler crashes.

```text
java.lang.NullPointerException: NAME import 2:0  [length: 41] [source_file: filename.js] : Color{id=0, debugInfo=DebugInfo{className=unknown, filename=}, prototypes=[], instanceColors=[], disambiguationSupertypes=[], invalidating=true, propertiesKeepOriginalName=false, constructor=false, ownProperties=[], boxId=null, closureAssert=false, unionElements=[]}
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:897)
	at com.google.javascript.jscomp.RemoveUnusedCode.getVarForNameNode(RemoveUnusedCode.java:891)
	at com.google.javascript.jscomp.RemoveUnusedCode.traverseNameNode(RemoveUnusedCode.java:746)
	at com.google.javascript.jscomp.RemoveUnusedCode.traverseNode(RemoveUnusedCode.java:571)
	at com.google.javascript.jscomp.RemoveUnusedCode.traverseChildren(RemoveUnusedCode.java:1301)
	at com.google.javascript.jscomp.RemoveUnusedCode.traverseCall(RemoveUnusedCode.java:803)
	at com.google.javascript.jscomp.RemoveUnusedCode.traverseNode(RemoveUnusedCode.java:498)
	at com.google.javascript.jscomp.RemoveUnusedCode.traverseChildren(RemoveUnusedCode.java:1301)
	at com.google.javascript.jscomp.RemoveUnusedCode.traverseNode(RemoveUnusedCode.java:581)
	at com.google.javascript.jscomp.RemoveUnusedCode.traverseChildren(RemoveUnusedCode.java:1301)
	at com.google.javascript.jscomp.RemoveUnusedCode.traverseNode(RemoveUnusedCode.java:581)
	at com.google.javascript.jscomp.RemoveUnusedCode.traverseChildren(RemoveUnusedCode.java:1301)
	at com.google.javascript.jscomp.RemoveUnusedCode.traverseNode(RemoveUnusedCode.java:581)
	at com.google.javascript.jscomp.RemoveUnusedCode.access$1200(RemoveUnusedCode.java:83)
	at com.google.javascript.jscomp.RemoveUnusedCode$Continuation.apply(RemoveUnusedCode.java:1806)
	at com.google.javascript.jscomp.RemoveUnusedCode.traverseAndRemoveUnusedReferences(RemoveUnusedCode.java:412)
	at com.google.javascript.jscomp.RemoveUnusedCode.process(RemoveUnusedCode.java:386)
	at com.google.javascript.jscomp.PhaseOptimizer$NamedPass.process(PhaseOptimizer.java:317)
	at com.google.javascript.jscomp.PhaseOptimizer$Loop.process(PhaseOptimizer.java:462)
	at com.google.javascript.jscomp.PhaseOptimizer.process(PhaseOptimizer.java:232)
	at com.google.javascript.jscomp.Compiler.performOptimizations(Compiler.java:2442)
	at com.google.javascript.jscomp.Compiler.lambda$stage2Passes$1(Compiler.java:791)
	at com.google.javascript.jscomp.CompilerExecutor.lambda$runInCompilerThread$0(CompilerExecutor.java:101)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.lang.Thread.run(Thread.java:834)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:519)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:192)
```

### PR DESCRIPTION
**Pull request by ChadKillingsworth**
Allows a dynamic import alias to be specified but lets the compiler automatically provide the extern definition. Prevents other passes from crashing when the definition is not found.

Also allows an alias of "import" to be specified. Since "import" is a keyword, a definition cannot be provided in an extern as the file would fail to parse. The RewriteDynamicImports pass will manually inject the name into the externs without parsing. This effective allows dynamic imports to be used in output language levels lower than ES_2020.

Fixes #3829

### CODE REVIEW

File: src/com/google/javascript/jscomp/RewriteDynamicImports.java [hunk 1]
```diff
@@ -357,4 +375,82 @@ private void injectWrappingFunctionExtern() {
...
+   * for an existing definition. Qualified name aliases check for an existing definition of the
+   * root name only.
+   */
+  private class AliasInjectingTraversal extends NodeTraversal.AbstractPreOrderCallback {
+    @Override
+    public boolean shouldTraverse(NodeTraversal t, Node n, Node parent) {
+      checkState(aliasIsValid());
+
+      // If the extern is a simple name and already declared, there is nothing to do
+      if (NodeUtil.isValidSimpleName(alias) && t.getScope().getVar(alias) != null) {
```
Comment (brad4d) [inline src/com/google/javascript/jscomp/RewriteDynamicImports.java:392]: I'm suspicious that all of this work to get the types is for naught.
I'm pretty sure this pass is running before the type checking passes.
Check DefaultPassConfig.

I think you'd probably be better off to just inject some parsed code with appropriate JS doc.

Something like this

https://github.com/google/closure-compiler/blob/master/src/com/google/javascript/jscomp/CrossChunkMethodMotion.java#L139

Or else do the injection after type checking when the types will be present.

**Comment by brad4d** [comment]
@blickly would you be willing to take over this review?
Thanks

File: src/com/google/javascript/jscomp/RewriteDynamicImports.java (hunk 1 above)
Comment (ChadKillingsworth) [reply src/com/google/javascript/jscomp/RewriteDynamicImports.java:392]: It's definitely running after type checking:

 - [check types](https://github.com/google/closure-compiler/blob/7ce5df09a638fa1e31f3407b0d2db71fc20ae8f6/src/com/google/javascript/jscomp/DefaultPassConfig.java#L353)
 - [rewrite dynamic imports](https://github.com/google/closure-compiler/blob/7ce5df09a638fa1e31f3407b0d2db71fc20ae8f6/src/com/google/javascript/jscomp/DefaultPassConfig.java#L381)
 
It is more readable parsing synthetic code, but later passes then crash because they assume type information is present and it isn't.

File: src/com/google/javascript/jscomp/RewriteDynamicImports.java [hunk 2]
```diff
@@ -357,4 +375,82 @@ private void injectWrappingFunctionExtern() {
...
+        if (aliasVar != null) {
+          return false;
+        }
+        Node aliasRootNode =
+            astFactory.createSingleVarNameDeclaration(aliasRootName, astFactory.createObjectLit());
+        aliasRootNode.srcrefTree(externsRoot);
+        externsRoot.addChildToBack(aliasRootNode);
+
+        // Define the rest of the parts of the name
+        String[] aliasNameParts = alias.split("\\.");
```
Comment (blickly) [inline src/com/google/javascript/jscomp/RewriteDynamicImports.java:432]: We usually avoid String's `.split` method in favor of Guava's `Splitter.on('.')` instead.

File: src/com/google/javascript/jscomp/RewriteDynamicImports.java [hunk 3]
```diff
@@ -357,4 +375,82 @@ private void injectWrappingFunctionExtern() {
...
+
+      // Create the type of the import function
+      JSTypeRegistry registry = compiler.getTypeRegistry();
+      JSType unknownType = registry.getNativeType(JSTypeNative.UNKNOWN_TYPE);
+      JSType promiseType = registry.getNativeType(JSTypeNative.PROMISE_TYPE);
+      TemplatizedType promiseTemplatizedType =
+          registry.createTemplatizedType(promiseType.toObjectType(), ImmutableList.of(unknownType));
+      JSType stringType = registry.getNativeType(JSTypeNative.STRING_TYPE);
+
+      Node externsRoot = compiler.getSynthesizedExternsInputAtEnd().getAstRoot(compiler);
```
Comment (blickly) [inline src/com/google/javascript/jscomp/RewriteDynamicImports.java:404]: Is this a typo?  I see the compiler has a `getSynthesizedExternsInput` but no `getSynthesizedExternsInputAtEnd`

File: test/com/google/javascript/jscomp/RewriteDynamicImportsTest.java [hunk 4]
```diff
@@ -451,4 +456,162 @@ public void outputModulesInternalImportDifferentChunks_used() {
...
+    Node externs = externsAndJs.getFirstChild();
+    Node root = externsAndJs.getLastChild();
+    compiler.beforePass(this.getName());
+    getProcessor(compiler).process(externs, root);
+
+    Node syntheticExternsAtEnd = externs.getLastChild();
+    assertThat(syntheticExternsAtEnd).isNotNull();
+    assertThat(syntheticExternsAtEnd.isScript()).isTrue();
+    Node injectedAlias = syntheticExternsAtEnd.getFirstChild();
+    assertThat(injectedAlias).isNotNull();
```
Comment (blickly) [inline test/com/google/javascript/jscomp/RewriteDynamicImportsTest.java:512]: This assertion seems to be failing for me. Is it not for you?

**Review by blickly — COMMENTED** [review]
Sorry to miss this for so long.

File: src/com/google/javascript/jscomp/RewriteDynamicImports.java (hunk 2 above)
Comment (ChadKillingsworth) [reply src/com/google/javascript/jscomp/RewriteDynamicImports.java]: Easy fix - done.

File: src/com/google/javascript/jscomp/RewriteDynamicImports.java (hunk 3 above)
Comment (ChadKillingsworth) [reply src/com/google/javascript/jscomp/RewriteDynamicImports.java]: It had a `getSynthesizedExternsInputAtEnd` method when the PR was opened - but there's been a refactoring since then. I've updated the methods.

File: test/com/google/javascript/jscomp/RewriteDynamicImportsTest.java (hunk 4 above)
Comment (ChadKillingsworth) [reply test/com/google/javascript/jscomp/RewriteDynamicImportsTest.java:512]: It wasn't failing - but is now due to the synthetic externs changing.
