### PR TITLE
Fix negation in glob patterns

### LINKED ISSUE #1407: Cannot use globs when running the compiler.
Since 62ca536... I am no longer able to use globs for files when running the compiler:

Running this command used to work before that change:
```
java -jar ../../compiler/compiler.jar \
--flagfile=options/compile.ini \
--define "goog.json.USE_NATIVE_JSON=true" --define "goog.ui.Component.ALLOW_DETACHED_DECORATION=true" --define "goog.NATIVE_ARRAY_PROTOTYPES=true" --define "goog.array.ASSUME_NATIVE_FUNCTIONS=true" --define "goog.Promise.UNHANDLED_REJECTION_DELAY=-1"  --define "app.settings.RUN_AS_USER=false" --externs=../externs/material.js --generate_exports --export_local_property_definitions --language_in=ECMASCRIPT6 --language_out=ES3 --use_types_for_optimization --output_wrapper="(function(){%output%})();" \
--only_closure_dependencies \
--closure_entry_point=app \
--manage_closure_dependencies true \
--output_manifest build/app.filelist.txt \
--js_output_file /tmp/closure_compiler_build \
--js="js/**.js" --js="tpl/en/**.js" --js="../../templates/soyutils_usegoog.js" --js="../../library/closure/goog/**.js" --js="../../library/third_party/closure/goog/mochikit/async/deferred.js" --js="../../library/third_party/closure/goog/mochikit/async/deferredlist.js" --js="../pstj/animation/**.js" --js="../pstj/app/**.js" --js="../pstj/autogenerated/**.js" --js="../pstj/cast/**.js" --js="../pstj/color/**.js" --js="../pstj/config/**.js" --js="../pstj/control/**.js" --js="../pstj/date/**.js" --js="../pstj/debug/**.js" --js="../pstj/ds/**.js" --js="../pstj/element/**.js" --js="../pstj/error/**.js" --js="../pstj/fx/**.js" --js="../pstj/graphics/**.js" --js="../pstj/material/**.js" --js="../pstj/math/**.js" --js="../pstj/mvc/**.js" --js="../pstj/ng/**.js" --js="../pstj/object/**.js" --js="../pstj/options/**.js" --js="../pstj/resource/**.js" --js="../pstj/sourcegen/**.js" --js="../pstj/storage/**.js" --js="../pstj/style/**.js" --js="../pstj/themes/**.js" --js="../pstj/ui/**.js" --js="../smjs/ds/**.js" --js="../smjs/element/**.js" --js="../smjs/persistence/**.js" --js="../smjs/player/**.js" --js="../smjs/remotecontrol/**.js" --js="../smjs/transport/**.js" --js="../smjs/tv/**.js" --js="../smjs/widgets/**.js" --js="!**_test.js"
```

Now (after the mentioned change) it gives this:
```
ERROR - Cannot read: !**_test.js

ERROR - Cannot read: ../../library/closure/goog/**.js

ERROR - Cannot read: ../pstj/animation/**.js

ERROR - Cannot read: ../pstj/app/**.js

ERROR - Cannot read: ../pstj/autogenerated/**.js

ERROR - Cannot read: ../pstj/cast/**.js

ERROR - Cannot read: ../pstj/color/**.js

ERROR - Cannot read: ../pstj/config/**.js

ERROR - Cannot read: ../pstj/control/**.js

ERROR - Cannot read: ../pstj/date/**.js

ERROR - Cannot read: ../pstj/debug/**.js

ERROR - Cannot read: ../pstj/ds/**.js

ERROR - Cannot read: ../pstj/element/**.js

ERROR - Cannot read: ../pstj/error/**.js

ERROR - Cannot read: ../pstj/fx/**.js

ERROR - Cannot read: ../pstj/graphics/**.js

ERROR - Cannot read: ../pstj/material/**.js

ERROR - Cannot read: ../pstj/math/**.js

ERROR - Cannot read: ../pstj/mvc/**.js

ERROR - Cannot read: ../pstj/ng/**.js

ERROR - Cannot read: ../pstj/object/**.js

ERROR - Cannot read: ../pstj/options/**.js

ERROR - Cannot read: ../pstj/resource/**.js

ERROR - Cannot read: ../pstj/sourcegen/**.js

ERROR - Cannot read: ../pstj/storage/**.js

ERROR - Cannot read: ../pstj/style/**.js

ERROR - Cannot read: ../pstj/themes/**.js

ERROR - Cannot read: ../pstj/ui/**.js

ERROR - Cannot read: ../smjs/ds/**.js

ERROR - Cannot read: ../smjs/element/**.js

ERROR - Cannot read: ../smjs/persistence/**.js

ERROR - Cannot read: ../smjs/player/**.js

ERROR - Cannot read: ../smjs/remotecontrol/**.js

ERROR - Cannot read: ../smjs/transport/**.js

ERROR - Cannot read: ../smjs/tv/**.js

ERROR - Cannot read: ../smjs/widgets/**.js

ERROR - Cannot read: js/**.js

ERROR - Cannot read: tpl/en/**.js

ERROR - required entry point "app" never provided

39 error(s), 0 warning(s)
```

### PR DESCRIPTION
**Pull request by Dominator008**
Fixes #1407.

### CODE REVIEW

File: test/com/google/javascript/jscomp/CommandLineRunnerTest.java [hunk 1]
```diff
@@ -1139,6 +1139,42 @@ public void testGlobJs2() throws IOException {
     }
   }
 
+  public void testGlobJs3() throws IOException {
```
Comment (MatrixFrog) [inline test/com/google/javascript/jscomp/CommandLineRunnerTest.java]: Why not just include FlagUsageException in the `throws` here and then if it's thrown it will still count as a failure.

File: src/com/google/javascript/jscomp/CommandLineRunner.java [hunk 2]
```diff
@@ -1526,10 +1538,12 @@ private static void matchPaths(String pattern, final Set<String> allJsInputs)
           @Override public FileVisitResult visitFile(
               Path p, BasicFileAttributes attrs) {
             if (matcher.matches(p.normalize())) {
+              String pathString = p.toString();
               if (remove) {
-                allJsInputs.remove(p.toString());
-              } else {
-                allJsInputs.add(p.toString());
+                excludes.add(pathString);
+		allJsInputs.remove(pathString);
```
Comment (MatrixFrog) [inline src/com/google/javascript/jscomp/CommandLineRunner.java]: +1 space indentation

File: test/com/google/javascript/jscomp/CommandLineRunnerTest.java (hunk 1 above)
Comment (Dominator008) [inline test/com/google/javascript/jscomp/CommandLineRunnerTest.java]: Done. We can clean up other tests later.

File: src/com/google/javascript/jscomp/CommandLineRunner.java (hunk 2 above)
Comment (Dominator008) [inline src/com/google/javascript/jscomp/CommandLineRunner.java]: Done.
