### PR TITLE
Fix support of glob pattern in --js

### LINKED ISSUE #1407: Cannot use globs when running the compiler.
Since 62ca536... I am no longer able to use globs for files when running the compiler:

Running this command used to work before that change:
```
java -jar ../../compiler/compiler.jar \
--flagfile=options/compile.ini \
--define "goog.json.USE_NATIVE_JSON=true" --define "goog.ui.Component.ALLOW_DETACHED_DECORATION=true" --define "goog.NATIVE_ARRAY_PROTOTYPES=true" --define "goog.array.ASSUME_NATIVE_FUNCTIONS=true" --define "goog.Promise.UNHANDLED_REJECTION_DELAY=-1"  --define "app.settings.RUN_AS_USER=false" --externs=../externs/material.js --generate_exports --export_local_property_definitions --language_in=ECMASCRIPT6 --language_out=ES3 --use_types_for_optimization --output_wrapper="(function(){%output%})();" \
--only_closure_dependencies \
--closure_entry_point=app \
--manage_closure_dependencies true \
--output_manifest build/app.filelist.txt \
--js_output_file /tmp/closure_compiler_build \
--js="js/**.js" --js="tpl/en/**.js" --js="../../templates/soyutils_usegoog.js" --js="../../library/closure/goog/**.js" --js="../../library/third_party/closure/goog/mochikit/async/deferred.js" --js="../../library/third_party/closure/goog/mochikit/async/deferredlist.js" --js="../pstj/animation/**.js" --js="../pstj/app/**.js" --js="../pstj/autogenerated/**.js" --js="../pstj/cast/**.js" --js="../pstj/color/**.js" --js="../pstj/config/**.js" --js="../pstj/control/**.js" --js="../pstj/date/**.js" --js="../pstj/debug/**.js" --js="../pstj/ds/**.js" --js="../pstj/element/**.js" --js="../pstj/error/**.js" --js="../pstj/fx/**.js" --js="../pstj/graphics/**.js" --js="../pstj/material/**.js" --js="../pstj/math/**.js" --js="../pstj/mvc/**.js" --js="../pstj/ng/**.js" --js="../pstj/object/**.js" --js="../pstj/options/**.js" --js="../pstj/resource/**.js" --js="../pstj/sourcegen/**.js" --js="../pstj/storage/**.js" --js="../pstj/style/**.js" --js="../pstj/themes/**.js" --js="../pstj/ui/**.js" --js="../smjs/ds/**.js" --js="../smjs/element/**.js" --js="../smjs/persistence/**.js" --js="../smjs/player/**.js" --js="../smjs/remotecontrol/**.js" --js="../smjs/transport/**.js" --js="../smjs/tv/**.js" --js="../smjs/widgets/**.js" --js="!**_test.js"
```

Now (after the mentioned change) it gives this:
```
ERROR - Cannot read: !**_test.js

ERROR - Cannot read: ../../library/closure/goog/**.js

ERROR - Cannot read: ../pstj/animation/**.js

ERROR - Cannot read: ../pstj/app/**.js

ERROR - Cannot read: ../pstj/autogenerated/**.js

ERROR - Cannot read: ../pstj/cast/**.js

ERROR - Cannot read: ../pstj/color/**.js

ERROR - Cannot read: ../pstj/config/**.js

ERROR - Cannot read: ../pstj/control/**.js

ERROR - Cannot read: ../pstj/date/**.js

ERROR - Cannot read: ../pstj/debug/**.js

ERROR - Cannot read: ../pstj/ds/**.js

ERROR - Cannot read: ../pstj/element/**.js

ERROR - Cannot read: ../pstj/error/**.js

ERROR - Cannot read: ../pstj/fx/**.js

ERROR - Cannot read: ../pstj/graphics/**.js

ERROR - Cannot read: ../pstj/material/**.js

ERROR - Cannot read: ../pstj/math/**.js

ERROR - Cannot read: ../pstj/mvc/**.js

ERROR - Cannot read: ../pstj/ng/**.js

ERROR - Cannot read: ../pstj/object/**.js

ERROR - Cannot read: ../pstj/options/**.js

ERROR - Cannot read: ../pstj/resource/**.js

ERROR - Cannot read: ../pstj/sourcegen/**.js

ERROR - Cannot read: ../pstj/storage/**.js

ERROR - Cannot read: ../pstj/style/**.js

ERROR - Cannot read: ../pstj/themes/**.js

ERROR - Cannot read: ../pstj/ui/**.js

ERROR - Cannot read: ../smjs/ds/**.js

ERROR - Cannot read: ../smjs/element/**.js

ERROR - Cannot read: ../smjs/persistence/**.js

ERROR - Cannot read: ../smjs/player/**.js

ERROR - Cannot read: ../smjs/remotecontrol/**.js

ERROR - Cannot read: ../smjs/transport/**.js

ERROR - Cannot read: ../smjs/tv/**.js

ERROR - Cannot read: ../smjs/widgets/**.js

ERROR - Cannot read: js/**.js

ERROR - Cannot read: tpl/en/**.js

ERROR - required entry point "app" never provided

39 error(s), 0 warning(s)
```

### PR DESCRIPTION
**Pull request by Dominator008**
Fixes #1407.

### CODE REVIEW

File: src/com/google/javascript/jscomp/AbstractCommandLineRunner.java [hunk 1]
```diff
@@ -1994,28 +1994,6 @@ CommandLineConfig setExterns(List<String> externs) {
       return this;
     }
 
-    private final List<String> js = new ArrayList<>();
```
Comment (MatrixFrog) [inline src/com/google/javascript/jscomp/AbstractCommandLineRunner.java]: Are you removing this stuff because it appears to be unused? I think it's used from the internal command line runner.

Comment (Dominator008) [inline src/com/google/javascript/jscomp/AbstractCommandLineRunner.java]: Yes. Added them back for now.

**Comment by Dominator008** [comment]
This should fix the Travis failure in Closure Library: https://travis-ci.org/google/closure-library

**Comment by joeltine** [comment]
Thx for the fix! Is there a workaround we can use until this is out? This permanently breaks the Closure Library Travis build.

**Comment by joeltine** [comment]
This appears to have not fixed the problem fully. Globs w/ negation are not being processed properly. All of the globs prefixed with "!" in the following command aren't being ignored by the compiler:

```
java -jar ../closure-compiler/build/compiler.jar \
  -O ADVANCED \
  --warning_level VERBOSE \
  --jscomp_error='*' \
  --jscomp_off=inferredConstCheck \
  --jscomp_off=extraRequire \
  --jscomp_off=unnecessaryCasts \
  --jscomp_off=deprecated \
  --jscomp_off=lintChecks \
  --js='**.js' \
  --js='!**_test.js' \
  --js='!**_perf.js' \
  --js='!**tester.js' \
  --js='!**promise/testsuiteadapter.js' \
  --js='!**osapi/osapi.js' \
  --js='!**svgpan/svgpan.js' \
  --js='!**alltests.js' \
  --js='!**\./node_modules**.js' \
  --js='!**protractor_spec.js' \
  --js='!**protractor.conf.js' \
  --js='!**browser_capabilities.js' \
  --js_output_file=$(mktemp);
```
