### PR TITLE
Force rewriting of ES6 or CommonJS modules which are imported

### LINKED ISSUE #1220: When using ECMAScript 6 modules, cannot import a module that has no exports
Consider these two modules:

```
// foo.js
alert("Hi");
```

```
// bar.js
import "./foo";
```

----

When compiling with `--language_in ECMASCRIPT6` I get the following error:

```
bar.js:1: ERROR - required "module$foo" namespace never provided
import "./foo";
^
```

However, if I add an export to `foo.js`, then it works correctly:

```
// foo.js
alert("Hi");

export const foo = 1;
```

----

In my application, I'm using `import "..."` to import a module solely for its side effects, so of course the module doesn't export anything, which is how I found this error.

### PR DESCRIPTION
**Pull request by ChadKillingsworth**
A file is considered a module if it is imported (whether it exports anything or not). This forces module rewriting to occur on files which are imported, but were otherwise unrecognized as a module.

This is accomplished by assuming that after module rewriting, any input that has no provide statements is a potential module. The normalized module identifier for each of these inputs is calculated. If any input attempts to require the normalized module name for one of these files, the file is treated as an ES6 module and rewriting is forced. Since the module didn't export anything, it doesn't matter which type of module it is rewritten as.

This PR also removes the `USELESS_USE_STRICT_DIRECTIVE` warning for ES6 modules. As a file can now be treated as a script or a module. This caused warnings when such code was imported. In addition, "use strict" directives are often inserted by IDE tools automatically and are already removed by the compiler.

Fixes #1220

[Review on Reviewable](https://reviewable.io/reviews/google/closure-compiler/1476)

### CODE REVIEW

**Comment by Dominator008** [comment]
Seems like the AST themselves are different. Tree2 has something from app.js while tree1 doesn't?

**Comment by ChadKillingsworth** [comment]
@Dominator008 Thanks - it was the extra `'use strict';`. I was staring at it far too long.

File: src/com/google/javascript/jscomp/Compiler.java [hunk 1]
```diff
@@ -1318,6 +1318,40 @@ Node parseInputs() {
         processAMDAndCommonJSModules();
       }
 
+      if (options.lowerFromEs6() || options.transformAMDToCJSModules ||
```
Comment (Dominator008) [inline src/com/google/javascript/jscomp/Compiler.java]: "||" should be on a new line according to https://google.github.io/styleguide/javaguide.html#s4.5.1-line-wrapping-where-to-break

File: src/com/google/javascript/jscomp/ProcessCommonJSModules.java [hunk 2]
```diff
@@ -305,9 +305,19 @@ private void visitRequireCall(NodeTraversal t, Node require, Node parent) {
...
       String moduleName = ES6ModuleLoader.toModuleName(loadAddress);
-      Node moduleRef = IR.name(moduleName).srcref(require);
-      parent.replaceChild(require, moduleRef);
       Node script = getCurrentScriptNode(parent);
+
+      // When require("name") is used as a standalone statement (the result isn't used)
+      // it indicates that a module is being loaded for the side effects it produces.
+      // In this case the require statement should just be removed as the goog.require
+      // call inserted will import the module.
+      if (!NodeUtil.isExpressionResultUsed(require) && parent.isExprResult() &&
```
Comment (Dominator008) [inline src/com/google/javascript/jscomp/ProcessCommonJSModules.java]: "&&" should be on a new line according to https://google.github.io/styleguide/javaguide.html#s4.5.1-line-wrapping-where-to-break

**Comment by ChadKillingsworth** [comment]
Review status: 0 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/com/google/javascript/jscomp/Compiler.java, line 1321 \[r1\]](https://reviewable.io:443/reviews/google/closure-compiler/1476#-K9jf26rCY_Q7mkrUvgS-r1-1321:-KA2euoS6hYWoc0pPXlM:-499146009) ([raw file](https://github.com/google/closure-compiler/blob/f2d5ddc3a563a5a35309a3dee4d07a7ec51b6ccb/src/com/google/javascript/jscomp/Compiler.java#L1321)):*
Done.

---

*[src/com/google/javascript/jscomp/ProcessCommonJSModules.java, line 314 \[r1\]](https://reviewable.io:443/reviews/google/closure-compiler/1476#-K9jf26rCY_Q7mkrUvgT-r1-314:-KA2ep7kw_HCsxOPoPQj:-499146009) ([raw file](https://github.com/google/closure-compiler/blob/f2d5ddc3a563a5a35309a3dee4d07a7ec51b6ccb/src/com/google/javascript/jscomp/ProcessCommonJSModules.java#L314)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/google/closure-compiler/1476)*

**Comment by ChadKillingsworth** [comment]
Ping @MatrixFrog

**Comment by MatrixFrog** [comment]
How urgent would you say this is?

File: src/com/google/javascript/jscomp/Compiler.java [hunk 3]
```diff
@@ -1318,6 +1318,40 @@ Node parseInputs() {
...
+
+          inputModuleIdentifiers.put(modInfo.getClosureNamespace(), input);
+        }
+
+        // Find out if any input attempted to import a module that had no exports.
+        // In this case we must force module rewriting to occur on the imported file
+        Map<String, CompilerInput> inputsToRewrite = new HashMap<>();
+        for (CompilerInput input : inputs) {
+          for (String require : input.getRequires()) {
+            if (inputModuleIdentifiers.containsKey(require) &&
```
Comment (Dominator008) [inline src/com/google/javascript/jscomp/Compiler.java]: `&&` should be on the next line.

**Comment by ChadKillingsworth** [comment]
It's a key piece of the module work I'm doing and it's blocking further work. Is this particularly difficult to land for some reason?

**Comment by MatrixFrog** [comment]
I just need to find the time to review it.

File: src/com/google/javascript/jscomp/Compiler.java [hunk 4]
```diff
@@ -1318,6 +1318,40 @@ Node parseInputs() {
...
+                !inputsToRewrite.containsKey(require)) {
+              inputsToRewrite.put(require, inputModuleIdentifiers.get(require));
+            }
+          }
+        }
+
+        if (inputsToRewrite.size() > 0) {
```
Comment (MatrixFrog) [inline src/com/google/javascript/jscomp/Compiler.java]: if (!inputsToRewrite.isEmpty())

File: src/com/google/javascript/jscomp/ProcessEs6Modules.java [hunk 5]
```diff
@@ -110,13 +106,21 @@ public ProcessEs6Modules(Compiler compiler, ES6ModuleLoader loader,
     this.reportDependencies = reportDependencies;
   }
 
-  public void processFile(Node root) {
+  /**
+   * If a file contains an ES6 "import" or "export" statement, or the forceRewrite
+   * option is true, rewrite the source as a module.
+   *
+   * @param root
+   * @param forceRewrite
```
Comment (MatrixFrog) [inline src/com/google/javascript/jscomp/ProcessEs6Modules.java]: Leave these off unless there is more to say about them. No requirement in Java to have a `@param` for every param.

**Comment by MatrixFrog** [comment]
lgtm with the changes mentioned. Sorry for the delay.

File: src/com/google/javascript/jscomp/Compiler.java (hunk 3 above)
Comment (ChadKillingsworth) [inline src/com/google/javascript/jscomp/Compiler.java]: Done

File: src/com/google/javascript/jscomp/ProcessEs6Modules.java (hunk 5 above)
Comment (ChadKillingsworth) [inline src/com/google/javascript/jscomp/ProcessEs6Modules.java]: They are auto-generated by my IDE. Removed.

**Comment by ChadKillingsworth** [comment]
Reviewed 2 of 2 files at r3.
Review status: 2 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/google/closure-compiler/1476)*

**Comment by ChadKillingsworth** [comment]
Reviewed 3 of 6 files at r1, 1 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/google/closure-compiler/1476)*

**Comment by ChadKillingsworth** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/com/google/javascript/jscomp/Compiler.java, line 1350 \[r4\]](https://reviewable.io:443/reviews/google/closure-compiler/1476#-KAyz8s1e4oVUdY6yfuT:-KAyz8s1e4oVUdY6yfuU:-846548440) ([raw file](https://github.com/google/closure-compiler/blob/7d5df41b3b7f3271ab0b2e40f93d10977927ea2d/src/com/google/javascript/jscomp/Compiler.java#L1350)):*
Got in a hurry and forgot to add the negation when I changed this to `isEmpty()` rather than `size() > 0`

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/google/closure-compiler/1476)*
